#!/bin/bash

# 🔑 Manual Firebase Service Account Setup Guide
# This script guides you through setting up service accounts manually

echo "🔑 Manual Firebase Service Account Setup"
echo "========================================"

echo ""
echo "📋 Step 1: Generate Service Account Keys"
echo "========================================"
echo ""
echo "1. Go to Firebase Console: https://console.firebase.google.com/"
echo ""
echo "2. For STAGING project (fitness-app-bupe-staging):"
echo "   - Select project: fitness-app-bupe-staging"
echo "   - Go to Project Settings (gear icon)"
echo "   - Click 'Service accounts' tab"
echo "   - Click 'Generate new private key'"
echo "   - Download the JSON file"
echo "   - Save it as: staging-service-account.json"
echo ""
echo "3. For PRODUCTION project (fitness-app-bupe-production):"
echo "   - Switch to project: fitness-app-bupe-production"
echo "   - Go to Project Settings (gear icon)"
echo "   - Click 'Service accounts' tab"
echo "   - Click 'Generate new private key'"
echo "   - Download the JSON file"
echo "   - Save it as: production-service-account.json"
echo ""

echo "📋 Step 2: Add to GitHub Secrets"
echo "================================"
echo ""
echo "1. Go to GitHub Repository: https://github.com/BUPE-NONDO/fitnessapp"
echo "2. Click Settings → Secrets and variables → Actions"
echo "3. Click 'New repository secret'"
echo ""
echo "4. Add STAGING secret:"
echo "   - Name: FIREBASE_SERVICE_ACCOUNT_FITNESS_APP_BUPE_STAGING"
echo "   - Value: Copy entire content of staging-service-account.json"
echo ""
echo "5. Add PRODUCTION secret:"
echo "   - Name: FIREBASE_SERVICE_ACCOUNT_FITNESS_APP_BUPE_PRODUCTION"
echo "   - Value: Copy entire content of production-service-account.json"
echo ""

echo "📋 Step 3: Set Up Environment Protection"
echo "========================================"
echo ""
echo "1. Go to: https://github.com/BUPE-NONDO/fitnessapp/settings/environments"
echo "2. Click 'New environment'"
echo "3. Name: production"
echo "4. Add protection rules if needed"
echo "5. Click 'Configure environment'"
echo ""

echo "📋 Step 4: Test the Setup"
echo "========================"
echo ""
echo "1. Make sure you're on dev branch:"
echo "   git checkout dev"
echo ""
echo "2. Make a small change:"
echo "   echo '# Test CI/CD' >> README.md"
echo ""
echo "3. Commit and push:"
echo "   git add README.md"
echo "   git commit -m '🧪 Test CI/CD pipeline'"
echo "   git push origin dev"
echo ""
echo "4. Check GitHub Actions:"
echo "   https://github.com/BUPE-NONDO/fitnessapp/actions"
echo ""

echo "🎯 Success Indicators:"
echo "====================="
echo "✅ GitHub Actions workflow runs successfully"
echo "✅ Staging deployment completes"
echo "✅ App is accessible at: https://fitness-app-bupe-staging.web.app"
echo "✅ Production deployment works when pushing to main"
echo ""

echo "🔗 Useful Links:"
echo "================"
echo "GitHub Actions: https://github.com/BUPE-NONDO/fitnessapp/actions"
echo "Staging Console: https://console.firebase.google.com/project/fitness-app-bupe-staging"
echo "Production Console: https://console.firebase.google.com/project/fitness-app-bupe-production"
echo ""

echo "📚 Documentation:"
echo "================"
echo "Quick Setup Guide: SETUP_CI_CD.md"
echo "Detailed Guide: docs/github-secrets-setup.md"
echo ""

echo "🎉 Ready to set up your service accounts!"
